version: '3.9'

services:
  web:
    build: ./shop
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_USER=q
      - POSTGRES_PASSWORD=q
      - POSTGRES_DB=q_dev

volumes:
  postgres_data:
